/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./assets/jar.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, MeshTransmissionMaterial } from '@react-three/drei'
import { useControls } from 'leva';
import { useFrame } from '@react-three/fiber';

export function Jar(props) {
  const { nodes, materials } = useGLTF('/assets/jar.glb')

  // add customizable properties to glass material
  const glassMaterialProps = useControls({
    thickness: { value: 0.2, min: 0, max: 3, step: 0.05 },
    roughness: { value: 0, min: 0, max: 1, step: 0.1 },
    transmission: { value: 1, min: 0, max: 1, step: 0.1 },
    ior: { value: 1, min: 0, max: 1, step: 0.1 },
    chromaticAberration: { value: 0.02, min: 0, max: 1 },
    backside: { value: true }
  });

  const jarRef = useRef();
  useFrame( () => {
    jarRef.current.rotation.y += 0.001;
  })

  return (
    <group {...props} ref={jarRef} dispose={null}>
      <group position={[0, 2.068, 0]}>
        
        {/** glass part of jar */}
        <mesh geometry={nodes.Cube.geometry}>
          <MeshTransmissionMaterial {...glassMaterialProps} />
        </mesh>

        {/** Jar lid and rim */}
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Rim Material']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Rim Ring']} />
      </group>
    </group>
  )
}

useGLTF.preload('assets/jar.glb');
